In [5]:
import numpy as np
lst=[1,2,3,4,5]
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(lst)
print(type(lst))
print(arr*2)
print(lst*2)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
<class 'list'>
[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape) #shape ie in this case 3,3
print(arr.ndim) #dimension of a matrix
print(arr.size) # total elements
print(arr.dtype)
np.zeros((2,2))
np.ones((3,3))
np.full((3,3),7)
identitiy_matrix=np.eye(3) #identitiy matrix 
print(identitiy_matrix)
np.arange(1,20,2)
np.linspace(0,10,3) # give me 3 no between 0 and 10


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
int64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([ 0.,  5., 10.])

In [37]:
a=np.array([5,10,15,20,25])
print(a)
b=np.arange(5,26,5)
print(b)
c=np.full((3,3),1)
print(c)
d=np.array([[10,20],[30,40],[50,60]])
print(d.ndim)
print(d.shape)
print(d.size)
np.linspace(0,100,6)

[ 5 10 15 20 25]
[ 5 10 15 20 25]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
2
(3, 2)
6


array([  0.,  20.,  40.,  60.,  80., 100.])